#!/usr/bin/env python

import csv
import sys
from scipy.stats import fisher_exact

if __name__=='__main__':   
    data = []
    reader = csv.reader(sys.stdin)
    for row in reader:
        data.append([int(i) for i in row])
    
    oddsration, pvalue = fisher_exact(data)
    
    print('odds ratio: {}'.format(oddsration))
    print('pvalue : {}'.format(pvalue))
    if pvalue < 0.01:
        print('p < .01 (significant)')
    elif pvalue < 0.05:
        print('p < .05 (significant)')
    else:
        print('p > .05 (not significant)')
