#!/usr/bin/env python

import csv
import sys
from statistics import mean
import numpy

def best_fit_slope_and_intercept(xs, ys):
    m = (((mean(xs) * mean(ys)) - mean(xs * ys)) /
         ((mean(xs) * mean(xs)) - mean(xs * xs)))
    b = mean(ys) - m * mean(xs)

    return m, b
    
if __name__=='__main__':
    reader = csv.reader(sys.stdin)
    data = [int(i) for i in next(reader)]

    ys = numpy.array(data, dtype=numpy.float64)
    xs = numpy.array(range(0, len(data)), dtype=numpy.float64)
    
    
    m, b = best_fit_slope_and_intercept(xs, ys)
    y = (m * len(data)) + b
    sys.stdout.write('m = {}\nb = {}\ny = {}\n'.format(m, b, y))
